// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0drCBFps6Ys926dx57MitWE-8vNIu59M',
    appId: '1:887049669354:web:37472927ea345b53ac6593',
    messagingSenderId: '887049669354',
    projectId: 'evaapp-e5e49',
    authDomain: 'evaapp-e5e49.firebaseapp.com',
    storageBucket: 'evaapp-e5e49.firebasestorage.app',
    measurementId: 'G-C4C5YCYXQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTCcJprV1srdjO44EZgUuTr8daum0pMUY',
    appId: '1:887049669354:android:6862bee18a0121ebac6593',
    messagingSenderId: '887049669354',
    projectId: 'evaapp-e5e49',
    storageBucket: 'evaapp-e5e49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz5xnmzO5DrVKXdm_dmZUS2SFhPdZDoEc',
    appId: '1:887049669354:ios:3fdee8d53e5b3cf9ac6593',
    messagingSenderId: '887049669354',
    projectId: 'evaapp-e5e49',
    storageBucket: 'evaapp-e5e49.firebasestorage.app',
    iosBundleId: 'br.com.evasos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz5xnmzO5DrVKXdm_dmZUS2SFhPdZDoEc',
    appId: '1:887049669354:ios:237e64cffc7fbe67ac6593',
    messagingSenderId: '887049669354',
    projectId: 'evaapp-e5e49',
    storageBucket: 'evaapp-e5e49.firebasestorage.app',
    iosBundleId: 'br.com.eva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0drCBFps6Ys926dx57MitWE-8vNIu59M',
    appId: '1:887049669354:web:b42f4d67afc4c6d5ac6593',
    messagingSenderId: '887049669354',
    projectId: 'evaapp-e5e49',
    authDomain: 'evaapp-e5e49.firebaseapp.com',
    storageBucket: 'evaapp-e5e49.firebasestorage.app',
    measurementId: 'G-YWYHCKS78S',
  );

}